version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-ssl-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./routes.conf:/etc/nginx/routes.conf:ro
    environment:
      - PROXY_PROTOCOL_PARAM=${PROXY_PROTOCOL_PARAM:-off}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    driver: bridge